version: '3'

services:
  test-task:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eora_test_task_container
    ports:
      - 8888:8888
    volumes:
      - .:/home/vino